# Generated by Django 4.2.7 on 2024-10-13 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_is_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_verified",
        ),
    ]
