version: '3.10'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn umemployed.wsgi:application --bind 0.0.0.0:${PORT:-8000}"
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      DEBUG: "0"
      DJANGO_ALLOWED_HOSTS: "*"
      DB_NAME: umemployed
      DB_USER: umdb
      DB_PASSWORD: Ume!Db@2025$Secure
      DB_HOST: umemployed-database.postgres.database.azure.com
      DB_PORT: 5432
      REDIS_URL: rediss://:CJ4sjQCD3Lm86hod07HxWss0sbU9TlFdkAzCaNhQSuw=@umemployed-redis.redis.cache.windows.net:6380?ssl_cert_reqs=none
      REDIS_PASSWORD: CJ4sjQCD3Lm86hod07HxWss0sbU9TlFdkAzCaNhQSuw=
      SITE_URL: https://umemployed-f6fdddfffmhjhjcj.canadacentral-01.azurewebsites.net

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    image: nyuydinebill/umemployed:celery
    command: >
      sh -c "python manage.py migrate &&
             celery -A umemployed worker --loglevel=info"
    volumes:
      - .:/app
      - ./media:/app/media
    environment:
      DEBUG: "0"
      DJANGO_ALLOWED_HOSTS: "*"
      DB_NAME: umemployed
      DB_USER: umdb
      DB_PASSWORD: Ume!Db@2025$Secure
      DB_HOST: umemployed-database.postgres.database.azure.com
      DB_PORT: 5432
      REDIS_URL: rediss://:CJ4sjQCD3Lm86hod07HxWss0sbU9TlFdkAzCaNhQSuw=@umemployed-redis.redis.cache.windows.net:6380?ssl_cert_reqs=none
      REDIS_PASSWORD: CJ4sjQCD3Lm86hod07HxWss0sbU9TlFdkAzCaNhQSuw=
      SITE_URL: https://umemployed-f6fdddfffmhjhjcj.canadacentral-01.azurewebsites.net
    depends_on:
      - web
