version: '3.10'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn umemployed.wsgi:application --bind 0.0.0.0:$PORT"
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      DEBUG: "0"
      DJANGO_ALLOWED_HOSTS: "*"
      DB_NAME: umemployed
      DB_USER: umdb
      DB_PASSWORD: Ume!Db@2025$Secure
      DB_HOST: umemployed-database.postgres.database.azure.com
      DB_PORT: 5432
      REDIS_URL: redis://:Rxiw0vK90aogJodr7J78sMoAoU8nYKmI7AzCaPRk7tI@umemployed-cache.redis.cache.windows.net:6380?ssl=true
      SITE_URL: https://umemployed.azurewebsites.net

