# Generated by Django 5.1.5 on 2025-05-23 13:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0005_dailyusage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="daily_limit",
        ),
    ]
