# Generated by Django 5.1.5 on 2025-06-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0007_alter_transaction_candidate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="tier",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("standard", "Standard"),
                    ("premium", "Premium"),
                    ("custom", "Custom"),
                    ("endorsement", "Endorsement"),
                ],
                max_length=20,
            ),
        ),
    ]
