# Generated by Django 4.2.7 on 2024-04-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
