# Generated by Django 4.2.7 on 2023-11-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='media/resume/images/PXL_20231104_141008232.MP.jpg', upload_to='resume/images'),
        ),
    ]
