# Generated by Django 4.2.7 on 2024-07-07 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0004_rename_est_date_company_founded_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
