# Generated by Django 4.2.7 on 2024-07-13 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_created_at_company_updated_at'),
    ]

    operations = [
    ]
