# Generated by Django 4.2.7 on 2024-08-18 00:11

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0007_alter_company_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="about_us",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="company",
            old_name="headquarters",
            new_name="location",
        ),
        migrations.AddField(
            model_name="company",
            name="country",
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
