# Generated by Django 4.2.7 on 2024-12-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
