# Generated by Django 5.1.1 on 2024-09-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created']},
        ),
    ]
