# Generated by Django 5.1.1 on 2024-09-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='idd',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
