# Generated by Django 4.2.7 on 2023-11-11 08:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import resume.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.skillcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(default='2023-11-11', null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('description', models.TextField(default='I am a ...', max_length=500)),
                ('profile_image', models.ImageField(blank=True, default='media/resume/images/PXL_20231104_141008232.MP.jpg', upload_to='resume/images')),
                ('cv', models.FileField(default='', upload_to='resume/cv', validators=[django.core.validators.FileExtensionValidator(['pdf']), resume.models.validate_file_mime_type])),
                ('experience', models.CharField(default='None', max_length=250, null=True)),
                ('education', models.CharField(default='None', max_length=50, null=True)),
                ('category', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.skillcategory')),
                ('skills', models.ManyToManyField(to='resume.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
