# Generated by Django 4.2.7 on 2024-04-26 22:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resumedoc',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
