# Generated by Django 4.2.7 on 2023-11-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='cv',
            field=models.FileField(default='', upload_to='resume/cv'),
        ),
        migrations.AddField(
            model_name='resume',
            name='date_of_birth',
            field=models.DateField(default='2023-11-07'),
        ),
        migrations.AddField(
            model_name='resume',
            name='profile_image',
            field=models.ImageField(blank=True, default='', upload_to='resume/images'),
        ),
    ]
