# Generated by Django 4.2.7 on 2023-11-07 16:22

import django.core.validators
from django.db import migrations, models
import resume.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_cv_resume_date_of_birth_resume_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='cv',
            field=models.FileField(default='', upload_to='resume/cv', validators=[django.core.validators.FileExtensionValidator(['pdf']), resume.models.validate_file_mime_type]),
        ),
    ]
