# Generated by Django 4.2.7 on 2023-11-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_remove_resume_education_remove_resume_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='date_of_birth',
            field=models.DateField(default='2023-11-12', null=True),
        ),
    ]
