# Generated by Django 4.2.7 on 2024-05-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_resume_id_alter_resumedoc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='date_of_birth',
            field=models.DateField(default='2024-05-01', null=True),
        ),
    ]
