# Generated by Django 4.2.7 on 2023-11-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_resume_cv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='location',
            new_name='country',
        ),
        migrations.AddField(
            model_name='resume',
            name='description',
            field=models.TextField(default='I am a ...', max_length=500),
        ),
        migrations.AddField(
            model_name='resume',
            name='phone',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='resume',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
