# Generated by Django 4.2.7 on 2024-03-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_resume_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='date_of_birth',
            field=models.DateField(default='2024-03-08', null=True),
        ),
    ]
