# Generated by Django 4.2.7 on 2023-11-12 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_resume_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='resume',
        ),
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience_set', to='resume.experience'),
        ),
    ]
