# Generated by Django 4.2.7 on 2024-05-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0004_alter_resume_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="date_of_birth",
            field=models.DateField(default="2024-05-11", null=True),
        ),
    ]
