# Generated by Django 4.2.7 on 2023-11-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_rename_location_resume_country_resume_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.IntegerField(default='+123456789'),
        ),
    ]
