# Generated by Django 4.2.7 on 2023-11-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_resume_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
