# Generated by Django 4.2.7 on 2023-11-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_remove_resume_experience_experience_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='date_of_birth',
            field=models.DateField(default='2023-11-15', null=True),
        ),
    ]
