# Generated by Django 4.2.7 on 2023-11-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_alter_resume_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.AddField(
            model_name='skill',
            name='categories',
            field=models.ManyToManyField(to='resume.skillcategory'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='date_of_birth',
            field=models.DateField(default='2023-11-16', null=True),
        ),
    ]
