# Generated by Django 4.2.7 on 2024-05-23 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resume", "0007_rename_years_experience_role_experience_end_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workexperience",
            old_name="years",
            new_name="role",
        ),
        migrations.AddField(
            model_name="workexperience",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="resume",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="resume.resume"
            ),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="date_of_birth",
            field=models.DateField(default="2024-05-23", null=True),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_experiences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
