# Generated by Django 4.2.7 on 2023-11-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_remove_skill_category_skill_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='date_of_birth',
            field=models.DateField(default='2023-11-19', null=True),
        ),
    ]
