# Generated by Django 4.2.7 on 2024-05-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0008_rename_years_workexperience_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="field_of_study",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
