# Generated by Django 4.2.7 on 2024-06-01 22:53

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0009_education_field_of_study"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinfo",
            name="country",
            field=django_countries.fields.CountryField(default="CM", max_length=2),
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="job_title",
            field=models.CharField(default="Marketer", max_length=100),
        ),
        migrations.AlterField(
            model_name="resume",
            name="date_of_birth",
            field=models.DateField(default="2024-06-01", null=True),
        ),
    ]
