# Generated by Django 4.2.7 on 2024-04-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_alter_resume_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_extracted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resume',
            name='date_of_birth',
            field=models.DateField(default='2024-04-03', null=True),
        ),
    ]
