# Generated by Django 4.2.7 on 2023-11-07 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_skillcategory_skill_resume_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='resume.skillcategory'),
        ),
    ]
