# Generated by Django 4.2.7 on 2023-11-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_resume_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
