# Generated by Django 4.2.7 on 2024-04-12 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_alter_resume_date_of_birth_resumedoc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumedoc',
            old_name='text_content',
            new_name='extracted_text',
        ),
    ]
