# Generated by Django 4.2.7 on 2024-04-12 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_rename_text_content_resumedoc_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedoc',
            name='extracted_skills',
            field=models.ManyToManyField(blank=True, related_name='resume_extracted_skills', to='resume.skill'),
        ),
        migrations.AddField(
            model_name='resumedoc',
            name='job_title',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.skillcategory'),
        ),
    ]
