# Generated by Django 4.2.7 on 2024-04-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_resumedoc_extracted_skills_resumedoc_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumedoc',
            name='job_title',
        ),
    ]
