# Generated by Django 4.2.7 on 2024-04-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_alter_resume_date_of_birth_alter_resumedoc_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='date_of_birth',
            field=models.DateField(default='2024-04-19', null=True),
        ),
    ]
