# Generated by Django 4.2.7 on 2024-06-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0016_alter_resume_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="date_of_birth",
            field=models.DateField(default="2024-06-17", null=True),
        ),
    ]
