# Generated by Django 4.2.7 on 2024-06-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0020_alter_resume_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="date_of_birth",
            field=models.DateField(default="2024-06-30", null=True),
        ),
    ]
