# Generated by Django 4.2.7 on 2024-07-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0022_alter_resume_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="date_of_birth",
            field=models.DateField(default="2024-07-07", null=True),
        ),
    ]
