# Generated by Django 4.2.7 on 2024-07-16 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0027_alter_resume_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.skillcategory'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='date_of_birth',
            field=models.DateField(default='2024-07-16', null=True),
        ),
    ]
