# Generated by Django 4.2.7 on 2024-07-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0028_alter_contactinfo_job_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="date_of_birth",
            field=models.DateField(default="2024-07-18", null=True),
        ),
    ]
