# Generated by Django 4.2.7 on 2024-07-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0032_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="language",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="languages",
            field=models.ManyToManyField(related_name="users", to="resume.language"),
        ),
        migrations.AlterField(
            model_name="resume",
            name="date_of_birth",
            field=models.DateField(default="2024-07-26", null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
