# Generated by Django 4.2.7 on 2024-07-26 06:28

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0033_remove_userprofile_language_userprofile_languages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='languages',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.language')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.userprofile')),
            ],
        ),
    ]
