# Generated by Django 4.2.7 on 2024-08-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0034_remove_userprofile_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='date_of_birth',
            field=models.DateField(default='2024-08-07', null=True),
        ),
    ]
