# Generated by Django 4.2.7 on 2024-08-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0036_alter_resume_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="resumedoc",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
