# Generated by Django 4.2.7 on 2024-08-10 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0039_alter_resume_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="resume.skillcategory"
            ),
        ),
    ]
