# Generated by Django 4.2.7 on 2024-08-10 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0039_alter_resume_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.skillcategory'),
        ),
    ]
