# Generated by Django 4.2.15 on 2024-08-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0042_alter_resume_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="date_of_birth",
            field=models.DateField(default="2024-08-12", null=True),
        ),
    ]
