# Generated by Django 4.2.7 on 2024-09-29 14:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0055_alter_resume_cv_alter_resume_date_of_birth_and_more"),
        ("resume", "0055_alter_resume_date_of_birth"),
    ]

    operations = []
