# Generated by Django 4.2.7 on 2024-12-18 22:38

import django.core.validators
from django.db import migrations, models

import resume.models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0058_alter_resume_cv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resumedoc",
            name="file",
            field=models.FileField(
                upload_to="resumes/",
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf", "docx", "txt"]),
                    resume.models.validate_file_mime_type,
                ],
            ),
        ),
    ]
