# Generated by Django 4.2.7 on 2024-12-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0059_alter_resumedoc_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="degree",
            field=models.CharField(default="Not specified", max_length=100),
        ),
        migrations.AlterField(
            model_name="education",
            name="field_of_study",
            field=models.CharField(blank=True, default="Not specified", max_length=255, null=True),
        ),
    ]
