# Generated by Django 5.1.5 on 2025-02-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0062_resumeanalysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="resume_analysis_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
