# Generated by Django 5.1.5 on 2025-02-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0066_transcript_delete_transcriptdoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='reasoning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
