# Generated by Django 5.1.5 on 2025-03-15 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0069_job_application_jobmatch_profileview_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="job",
        ),
        migrations.RemoveField(
            model_name="application",
            name="user",
        ),
        migrations.RemoveField(
            model_name="jobmatch",
            name="job",
        ),
        migrations.RemoveField(
            model_name="jobmatch",
            name="user",
        ),
        migrations.RemoveField(
            model_name="skillendorsement",
            name="endorsed_by",
        ),
        migrations.RemoveField(
            model_name="skillendorsement",
            name="skill",
        ),
        migrations.RemoveField(
            model_name="skillendorsement",
            name="user",
        ),
        migrations.DeleteModel(
            name="Job",
        ),
        migrations.DeleteModel(
            name="Application",
        ),
        migrations.DeleteModel(
            name="JobMatch",
        ),
        migrations.DeleteModel(
            name="SkillEndorsement",
        ),
    ]
