# Generated by Django 5.1.5 on 2025-05-23 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0044_alter_job_salary_range"),
        ("resume", "0071_contactinfo_city_contactinfo_date_of_birth"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnhancedResume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("skills", models.JSONField(blank=True, null=True)),
                ("experience", models.JSONField(blank=True, null=True)),
                ("education", models.JSONField(blank=True, null=True)),
                ("certifications", models.JSONField(blank=True, null=True)),
                ("projects", models.JSONField(blank=True, null=True)),
                ("languages", models.JSONField(blank=True, null=True)),
                ("awards", models.JSONField(blank=True, null=True)),
                ("publications", models.JSONField(blank=True, null=True)),
                ("volunteer_experience", models.JSONField(blank=True, null=True)),
                ("interests", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="job.job"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
