# Generated by Django 5.1.5 on 2025-06-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0072_enhancedresume"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlanguage",
            name="proficiency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                    ("native", "Native"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
