# Generated by Django 5.1.5 on 2025-07-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0074_resumeenhancementtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='resume/covers'),
        ),
    ]
