# Generated by Django 4.2.7 on 2024-04-26 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("onboarding", "0001_initial"),
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizresponse",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="resume.resume"
            ),
        ),
        migrations.AddField(
            model_name="generalknowledgeanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="onboarding.generalknowledgequestion",
            ),
        ),
    ]
