# Generated by Django 4.2.7 on 2023-12-05 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_application_has_completed_quiz'),
        ('onboarding', '0002_quizresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresponse',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.application'),
        ),
    ]
