# Generated by Django 4.2.7 on 2023-12-05 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_application_has_completed_quiz'),
        ('onboarding', '0004_alter_quizresponse_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresponse',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_responses', to='job.application'),
        ),
    ]
