# Generated by Django 4.2.7 on 2023-12-08 10:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_alter_quizresponse_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresponse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
