# Generated by Django 4.2.7 on 2024-09-18 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('job_application', 'Job Application Received'), ('new_job_posted', 'New Job Posted'), ('endorsement', 'Endorsement Received'), ('interview_scheduled', 'Interview Scheduled'), ('account_alert', 'Account Security Alert'), ('upcoming_event', 'Upcoming Event Reminder'), ('new_message', 'New Message Received'), ('special_offer', 'Special Offer'), ('profile_updated', 'Profile Updated')], max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
