# Generated by Django 4.2.7 on 2024-03-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_score', models.IntegerField(default=0)),
                ('matching_percentage', models.FloatField(default=0.0)),
                ('overall_match_percentage', models.FloatField(default=0.0)),
                ('has_completed_quiz', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('salary', models.PositiveBigIntegerField(default=35000)),
                ('ideal_candidate', models.TextField()),
                ('is_available', models.BooleanField(default=False)),
                ('description', models.TextField(default='We are looking for ...', max_length=255)),
                ('responsibilities', models.TextField(default='You will be in charge of ...', max_length=255)),
                ('benefits', models.TextField(default='...')),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Mid', 'Mid'), ('Expert', 'Expert')], default='Beginner', max_length=10)),
            ],
        ),
    ]
