# Generated by Django 4.2.7 on 2023-12-12 21:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quiz_score', models.IntegerField(default=0)),
                ('matching_percentage', models.FloatField(default=0.0)),
                ('overall_match_percentage', models.FloatField(default=0.0)),
                ('has_completed_quiz', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('salary', models.PositiveBigIntegerField(default=35000)),
                ('ideal_candidate', models.TextField()),
                ('is_available', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
