# Generated by Django 4.2.7 on 2023-12-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0001_initial'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.ManyToManyField(to='resume.skill'),
        ),
    ]
