# Generated by Django 4.2.7 on 2023-11-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_remove_skill_category_skill_categories_and_more'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='requirements',
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.ManyToManyField(to='resume.skill'),
        ),
    ]
