# Generated by Django 4.2.7 on 2024-04-26 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("job", "0001_initial"),
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillquestion",
            name="skill",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="resume.skill"),
        ),
        migrations.AddField(
            model_name="savedjob",
            name="job",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="job.job"),
        ),
    ]
