# Generated by Django 4.2.7 on 2024-04-26 22:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantanswer',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skillquestion',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
