# Generated by Django 4.2.7 on 2023-12-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='overall_match_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
