# Generated by Django 4.2.7 on 2024-05-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0004_alter_applicantanswer_id_alter_application_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
