# Generated by Django 4.2.7 on 2023-12-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_application_id_alter_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='descriptions',
            field=models.TextField(default='We are looking for ...', max_length=255),
        ),
    ]
