# Generated by Django 4.2.7 on 2023-12-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_application_overall_match_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='has_completed_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
