# Generated by Django 4.2.7 on 2024-03-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_applicantanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantanswer',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
