# Generated by Django 4.2.7 on 2023-12-28 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_descriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='descriptions',
            new_name='description',
        ),
    ]
