# Generated by Django 4.2.7 on 2024-03-13 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_resume_date_of_birth'),
        ('job', '0006_applicantanswer_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_questions', to='resume.skillcategory'),
        ),
    ]
