# Generated by Django 4.2.7 on 2024-01-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_rename_descriptions_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=models.TextField(default='...'),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(default='You will be in charge of ...', max_length=255),
        ),
    ]
