# Generated by Django 4.2.7 on 2024-06-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_remove_application_round1_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='total_scores',
            field=models.JSONField(default=dict),
        ),
    ]
