# Generated by Django 4.2.7 on 2024-06-26 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0020_alter_resume_date_of_birth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0007_application_total_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'job', 'skill')},
            },
        ),
    ]
