# Generated by Django 4.2.7 on 2024-06-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_completedskills'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedskills',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
