# Generated by Django 4.2.7 on 2024-03-17 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_skillquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.skillquestion'),
        ),
    ]
