# Generated by Django 4.2.7 on 2024-06-26 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_alter_completedskills_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedskills',
            name='completed_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 4, 12, 20, 342768, tzinfo=datetime.timezone.utc)),
        ),
    ]
