# Generated by Django 4.2.7 on 2024-03-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_alter_applicantanswer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='round1_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='round2_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='round3_completed',
            field=models.BooleanField(default=False),
        ),
    ]
