# Generated by Django 4.2.7 on 2024-03-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_application_round1_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='round1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='round2_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='round3_score',
            field=models.IntegerField(default=0),
        ),
    ]
