# Generated by Django 4.2.7 on 2024-07-06 14:44

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0011_alter_completedskills_completed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completedskills",
            name="completed_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 6, 14, 44, 30, 34836, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
