# Generated by Django 4.2.7 on 2024-04-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_skill_is_extracted_alter_resume_date_of_birth'),
        ('job', '0011_application_round1_score_application_round2_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='extracted_skills',
            field=models.ManyToManyField(blank=True, related_name='extracted_jobs', to='resume.skill'),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.ManyToManyField(related_name='required_jobs', to='resume.skill'),
        ),
    ]
