# Generated by Django 4.2.7 on 2024-07-06 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_alter_completedskills_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hire_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('remote', 'Remote'), ('onsite', 'Onsite'), ('hybrid', 'Hybrid'), ('internship', 'Internship')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='completedskills',
            name='completed_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 14, 46, 0, 201084, tzinfo=datetime.timezone.utc)),
        ),
    ]
