# Generated by Django 4.2.7 on 2024-07-07 00:46

import datetime

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0013_job_hire_number_job_job_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="experience_levels",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="job",
            name="job_location_type",
            field=models.CharField(
                choices=[
                    ("remote", "Remote"),
                    ("onsite", "Onsite"),
                    ("hybrid", "Hybrid"),
                    ("internship", "Internship"),
                ],
                default=django.utils.timezone.now,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="shifts",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="job",
            name="weekly_ranges",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="completedskills",
            name="completed_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 7, 0, 45, 57, 873714, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
