# Generated by Django 4.2.7 on 2024-07-07 12:38

import datetime

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0015_alter_completedskills_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="job",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="completedskills",
            name="completed_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 7, 12, 37, 22, 871623, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
