# Generated by Django 4.2.7 on 2024-07-08 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_application_created_at_application_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedskills',
            name='completed_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 8, 16, 34, 43, 389710, tzinfo=datetime.timezone.utc)),
        ),
    ]
