# Generated by Django 4.2.7 on 2024-07-13 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_alter_completedskills_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedskills',
            name='completed_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 8, 59, 28, 774572, tzinfo=datetime.timezone.utc)),
        ),
    ]
