# Generated by Django 4.2.7 on 2024-07-14 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0020_alter_completedskills_completed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completedskills",
            name="completed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
