# Generated by Django 4.2.7 on 2024-07-19 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0021_alter_completedskills_completed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="job",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="job.job"),
        ),
    ]
