# Generated by Django 4.2.7 on 2024-08-07 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0023_applicantanswer_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillquestion',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_questions', to='job.job'),
        ),
    ]
