# Generated by Django 4.2.7 on 2024-08-10 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0024_skillquestion_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantanswer',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='job.application'),
        ),
    ]
