# Generated by Django 4.2.7 on 2024-08-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0026_alter_applicantanswer_id_alter_application_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcq",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="skillquestion",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
