# Generated by Django 4.2.7 on 2024-08-31 12:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0027_alter_mcq_id_alter_skillquestion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='benefits',
            field=ckeditor.fields.RichTextField(default='...'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=ckeditor.fields.RichTextField(default='We are looking for ...', max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='ideal_candidate',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsibilities',
            field=ckeditor.fields.RichTextField(default='You will be in charge of ...', max_length=1000),
        ),
    ]
