# Generated by Django 4.2.7 on 2024-09-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0028_alter_job_benefits_alter_job_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary_range',
            field=models.CharField(choices=[('30000-50000', '$30,000 - $50,000'), ('50001-70000', '$50,001 - $70,000'), ('70001-100000', '$70,001 - $100,000'), ('100001-150000', '$100,001 - $150,000'), ('150001+', '$150,001 and above')], default='30000-50000', max_length=20),
        ),
    ]
