# Generated by Django 4.2.7 on 2024-09-09 15:25

from django.db import migrations, models
import django_countries.fields
from django_ckeditor_5.fields import CKEditor5Field


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0030_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=CKEditor5Field(default='We are looking for ...', max_length=2000),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Full_time', 'Full-Time'), ('Part_time', 'Part-Time'), ('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Internship', 'Internship'), ('Freelance', 'Freelance')], max_length=20, verbose_name='Job Type'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
