# Generated by Django 4.2.7 on 2024-10-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0031_alter_job_description_alter_job_job_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
