# Generated by Django 4.2.7 on 2024-10-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0032_application_video_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("rejected", "Rejected"),
                    ("accepted", "Accepted"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
