# Generated by Django 4.2.7 on 2024-10-13 10:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0033_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='overall_match_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
