# Generated by Django 4.2.7 on 2024-10-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0034_alter_application_overall_match_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillquestion',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
