# Generated by Django 4.2.7 on 2024-11-12 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django_ckeditor_5.fields import CKEditor5Field

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0036_job_job_creation_is_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='responsibilities',
            field=CKEditor5Field(default='You will be in charge of ...', max_length=2000),
        ),
        migrations.CreateModel(
            name='Shortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortlisted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_shortlists', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_shortlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
