# Generated by Django 4.2.7 on 2024-11-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0038_retakerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='has_started',
            field=models.BooleanField(default=False),
        ),
    ]
