# Generated by Django 4.2.7 on 2024-11-24 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0058_alter_resume_cv"),
        ("job", "0039_application_has_started"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcq",
            name="job_title",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mcq_questions",
                to="resume.skillcategory",
            ),
        ),
        migrations.AlterField(
            model_name="retakerequest",
            name="job",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="job.job"
            ),
        ),
        migrations.AlterField(
            model_name="skillquestion",
            name="job",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="skill_questions",
                to="job.job",
            ),
        ),
    ]
