# Generated by Django 5.1.5 on 2025-04-28 19:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0042_rename_recruiter_rating_endorser_remove_rating_job_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortlist",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
