# Generated by Django 5.1.5 on 2025-05-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0043_shortlist_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="salary_range",
            field=models.CharField(
                choices=[
                    ("0-10000", "$0 - $10,000"),
                    ("10001-20000", "$10,001 - $20,000"),
                    ("20001-30000", "$20,001 - $30,000"),
                    ("30000-50000", "$30,000 - $50,000"),
                    ("50001-70000", "$50,001 - $70,000"),
                    ("70001-100000", "$70,001 - $100,000"),
                    ("100001-150000", "$100,001 - $150,000"),
                    ("150001+", "$150,001 and above"),
                ],
                default="30000-50000",
                max_length=20,
            ),
        ),
    ]
