# Generated by Django 5.1.5 on 2025-07-14 21:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0044_alter_job_salary_range'),
        ('resume', '0074_resumeenhancementtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='questions_generation_progress',
            field=models.JSONField(default=dict, help_text="Tracks which skills have questions generated: {'skill_id': True/False}"),
        ),
        migrations.AddField(
            model_name='skillquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skillquestion',
            name='source',
            field=models.CharField(choices=[('ai_generated', 'AI Generated'), ('fallback_pool', 'Fallback Pool'), ('manual', 'Manual')], default='ai_generated', help_text='Source of the question (AI generated, fallback pool, etc.)', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='skillquestion',
            unique_together={('job', 'skill', 'question')},
        ),
        migrations.CreateModel(
            name='QuestionPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('option_c', models.CharField(max_length=200)),
                ('option_d', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.skill')),
            ],
            options={
                'unique_together': {('skill', 'question')},
            },
        ),
        migrations.CreateModel(
            name='SkillGenerationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('ai_success', 'AI Generation Successful'), ('ai_failed', 'AI Generation Failed'), ('fallback_used', 'Fallback Questions Used'), ('generic_used', 'Generic Questions Used'), ('experience_based', 'Experience-Based Questions Used'), ('portfolio_only', 'Portfolio Review Only'), ('manual_required', 'Manual Intervention Required')], default='pending', max_length=20)),
                ('ai_attempts', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('questions_generated', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_statuses', to='job.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.skill')),
            ],
            options={
                'unique_together': {('job', 'skill')},
            },
        ),
    ]
