name: Build, Push and Deploy to Azure Container Instances

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: celeryworkerumemployed.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -f Dockerfile.celery -t celeryworkerumemployed.azurecr.io/celery-worker:latest .
        docker push celeryworkerumemployed.azurecr.io/celery-worker:latest

    - name: Azure CLI login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Container Instances
      run: |
        az container create \
          --resource-group UmEmployed_RG \
          --name celery-worker \
          --image celeryworkerumemployed.azurecr.io/celery-worker:latest \
          --registry-login-server celeryworkerumemployed.azurecr.io \
          --registry-username ${{ secrets.ACR_USERNAME }} \
          --registry-password ${{ secrets.ACR_PASSWORD }} \
          --restart-policy Always || \
        az container update \
          --resource-group UmEmployed_RG \
          --name celery-worker \
          --image celeryworkerumemployed.azurecr.io/celery-worker:latest
