name: Delete Old Artifacts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours instead of daily

permissions:
  actions: write  # ✅ Required for deleting artifacts
  contents: read  # ✅ Default needed for most actions

jobs:
  cleanup-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Delete artifacts older than 3 days, keep last 2
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '3 days'  # More aggressive: 3 days instead of 7
          skip-recent: 2  # Keep only last 2 instead of 5
