name: Delete Old Artifacts

on:
  schedule:
    - cron: '0 3 * * *' # Runs every day at 03:00 UTC
  workflow_dispatch:

jobs:
  delete-old-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Delete artifacts older than 7 days
        uses: c-hive/delete-artifacts@v2
        with:
          age: '7 days'
          skip-recent: 5