name: Deploy

on:
  workflow_run:
    workflows:
      - Build and deploy Python app to Azure Web App - umemployed
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Run Django commands
        env:
          AZURE_POSTGRESQL_CONNECTIONSTRING: ${{ secrets.AZURE_POSTGRESQL_CONNECTIONSTRING }}
        run: |
          python manage.py collectstatic --noinput
          python manage.py migrate
